name: ci

on:
  push:
  pull_request:

jobs:
  build:
    
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: macos-latest
          - os: ubuntu-latest

    runs-on: ${{ matrix.cfg.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - run: nix flake check
      - run: nix build
